### ISSUE TITLE
Compatibility with the newest Omnet version

### ISSUE THREAD

**Issue by PP90** [omnetpp/mixim#2]
I've tried to integrate Mixim as project in the Omnetpp version 5.When the Mimix project is built, some errors occur. My question is: this version of Mixim is compatible with the newest versions of Omnet ?

**Comment by rhornig** [comment]
No. MiXiM is no longer maintained and most likely it is not compatible with OMNeT 5. Almost all of the functionality of MiXiM was merget into INET 3.0 and the current version of INET 3.2.4 is working with OMNeT++ 5.0

**Comment by litao3rd** [comment]
so if i reinstall INET 3.0 in omnet, will MiXiM be compatibility with the newest omnet version ?

**Comment by litao3rd** [comment]
Hi do u mean that all of the functionality of MiXim was merged into INET3.0. So I don't need to use MiXiM if  I use INET 3.0 or later ?

**Comment by rhornig** [comment]
MiXiM will not become magically compatible with the latest OMNeT just by installing a new version of inet. What I mean is that all features of MiXiM was implemented new or merged into INET 3.x so there is no rason to use MiXiM at all.
